[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "fibonacci"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "cargo run"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends-on = ["fmt"] }

[dependencies]
rust = ">=1.83.0,<1.84"

